### ISSUE TITLE
Question: Lots of errors "wsarecv: An existing connection was forcibly closed by the remote host."

### ISSUE THREAD

**Issue by bvarnai** [saucelabs/forwarder#376]
I have a simple setup, http proxy with pac, only browser agents (Firefox 116.0.3 mainly). I have VPN, direct and upstream proxies are on VPN.

`forwarder run --pac "http://proxyconf/" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0
; Win64; x64)"`

I keep getting tons of errors (like it hogs the machine) on Windows 11, x64, version 1.0.2

> 2023/08/30 03:28:04 [proxy] ERROR: failed to read request: read tcp 172.30.235.203:3128->139.181.198.73:43028: wsarecv: An existing connection was forcibly closed by the remote host.
and
> 2023/08/30 03:28:48 [proxy] ERROR: failed to copy inbound CONNECT tunnel: readfrom tcp 192.168.48.243:3128->192.168.48.220:49453: read tcp 192.168.48.243:46234->52.113.205.120:443: wsarecv: An existing connection was forcibly closed by the remote host.

Firewall checked to my best knowledge, all traffic allowed. Sometimes it works for a while, than starts to rain errors. It's safe to assume it's getting worse with time, but not completely gone by a restart.

Any suggestions? Thanks!

**Comment by bvarnai** [comment]
Update: I tried the docker image on Windows, no sign of this error. This works for me, but maybe worth to investigate. At least it proves that it's not caused by local network/firewall or VPN issue.

**Comment by Choraden** [comment]
Hello, thank you for reporting. 
We will investigate this. 

In the meantime, you can try [v1.0.3](https://github.com/saucelabs/forwarder/releases/tag/v1.0.3) that has just been released.

**Comment by mmatczuk** [comment]
Hi @bvarnai the issue is fixed. Could you do me a favor and check if version v1.1-rc1 solves it for you?

**Comment by bvarnai** [comment]
I still experience these errors, however they are no longer flooding the console. Not a single one reported in docker.

**Comment by mmatczuk** [comment]
This error means that the client (browser) has disconnected

```
WSAECONNRESET
10054 (0x2746)
An existing connection was forcibly closed by the remote host.
```
https://learn.microsoft.com/en-us/windows/win32/debug/system-error-codes--9000-11999-

How do you experience the error now? Can you share more information and debug logs.

**Comment by mmatczuk** [comment]
It looks like we need to handle that also in tunnel.
It wrongly reports WSAECONNABORTED and WSAECONNRESET while reading and sending as errors.

<img width="1324" alt="Screenshot 2023-10-18 at 12 21 08" src="https://github.com/saucelabs/forwarder/assets/1617930/0f07044d-f933-43f6-ba70-8058b07093d4">

From client perspective things look OK

<img width="489" alt="Screenshot 2023-10-18 at 12 24 08" src="https://github.com/saucelabs/forwarder/assets/1617930/3ca45fcc-94c5-444b-a65c-d4092c0fe5e1">

**Comment by bvarnai** [comment]
Yes, from the client side everything seems to be ok. No issues in page loads etc. My console log looks similar to what you posted. I will provide my "actual" logs asap.

**Comment by mmatczuk** [comment]
Fixed in #471 will be released in rc2 (or ga).
